#! /bin/sh

sxhkd &
sh $HOME/.config/polybar/launch.sh

bspc monitor -d bspc monitor -d 一 二 三 四 五

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		50

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton &
