#! /bin/sh

sxhkd &
~/autostart.sh

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 一 二 三 四 五

bspc config border_width         2
bspc config window_gap          10

bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         20
bspc config right_padding        20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
